"""
Integrated Simulator - Bridges Consortium and Bilateral ABMs
============================================================

Allows bilateral friction between agent pairs to generate shocks
in the consortium simulation, creating realistic feedback loops.
"""

import random
from dataclasses import dataclass
from typing import Dict, List, Any, Optional, Tuple
from enum import Enum


@dataclass
class BilateralShock:
    """Shock generated by bilateral friction."""
    source_dyad: Tuple[str, str]
    friction_level: float
    shock_type: str
    intensity: float
    affected_agents: List[str]


class IntegratedSimulator:
    """
    Runs consortium simulation with bilateral friction feedback.
    
    Flow:
    1. Initialize bilateral friction state for specified dyads
    2. Each phase:
       a. Update bilateral friction
       b. Convert high friction to consortium shocks
       c. Run consortium phase step
       d. Check for bilateral-triggered defections
    """
    
    def __init__(
        self,
        consortium_config: Dict[str, Any],
        bilateral_configs: List[Dict[str, Any]],
        coupling_strength: float = 0.3,
        seed: Optional[int] = None
    ):
        self.consortium_config = consortium_config
        self.bilateral_configs = bilateral_configs
        self.coupling_strength = coupling_strength
        self.seed = seed
        
        # Track bilateral states
        self.bilateral_states: Dict[Tuple[str, str], Dict[str, float]] = {}
        
    def _init_bilateral_states(self):
        """Initialize bilateral friction tracking."""
        for config in self.bilateral_configs:
            dyad = (config.get("state_a", "A"), config.get("state_b", "B"))
            self.bilateral_states[dyad] = {
                "friction": config.get("initial_friction", 0.5),
                "cooperation": config.get("initial_cooperation", 0.3),
                "months_in_crisis": 0,
                "peak_friction": config.get("initial_friction", 0.5),
            }
    
    def _update_bilateral_friction(self, dyad: Tuple[str, str]) -> float:
        """Update friction for one dyad, return change."""
        state = self.bilateral_states[dyad]
        
        # Random walk with mean reversion
        drift = random.gauss(0, 0.05)
        mean_reversion = (0.5 - state["friction"]) * 0.1
        
        old_friction = state["friction"]
        state["friction"] = max(0.0, min(1.0, 
            state["friction"] + drift + mean_reversion
        ))
        
        # Track peak
        if state["friction"] > state["peak_friction"]:
            state["peak_friction"] = state["friction"]
        
        # Crisis detection
        if state["friction"] > 0.7:
            state["months_in_crisis"] += 1
        else:
            state["months_in_crisis"] = 0
        
        return state["friction"] - old_friction
    
    def _generate_bilateral_shocks(self) -> List[BilateralShock]:
        """Convert high bilateral friction to consortium shocks."""
        shocks = []
        
        for dyad, state in self.bilateral_states.items():
            friction = state["friction"]
            
            # Crisis threshold - generates shock
            if friction > 0.7 and random.random() < self.coupling_strength:
                shock = BilateralShock(
                    source_dyad=dyad,
                    friction_level=friction,
                    shock_type="bilateral_crisis",
                    intensity=friction * random.uniform(0.5, 1.0),
                    affected_agents=list(dyad)
                )
                shocks.append(shock)
            
            # Escalation - may trigger defection check
            elif friction > 0.85:
                shock = BilateralShock(
                    source_dyad=dyad,
                    friction_level=friction,
                    shock_type="bilateral_escalation",
                    intensity=friction * random.uniform(0.7, 1.0),
                    affected_agents=list(dyad)
                )
                shocks.append(shock)
        
        return shocks
    
    def run_integrated(self, n_months: int = 180) -> Dict[str, Any]:
        """
        Run integrated simulation.
        
        Returns summary including both consortium and bilateral outcomes.
        """
        if self.seed:
            random.seed(self.seed)
        
        self._init_bilateral_states()
        
        # Track history
        bilateral_history = []
        shock_history = []
        
        for month in range(n_months):
            # Update all bilateral dyads
            for dyad in self.bilateral_states.keys():
                self._update_bilateral_friction(dyad)
            
            # Generate shocks
            shocks = self._generate_bilateral_shocks()
            
            # Record
            bilateral_history.append({
                "month": month,
                "states": {
                    str(k): dict(v) for k, v in self.bilateral_states.items()
                }
            })
            
            if shocks:
                for shock in shocks:
                    shock_history.append({
                        "month": month,
                        "dyad": shock.source_dyad,
                        "type": shock.shock_type,
                        "intensity": shock.intensity
                    })
        
        # Summary
        return {
            "months_simulated": n_months,
            "bilateral_final_states": {
                str(k): dict(v) for k, v in self.bilateral_states.items()
            },
            "total_shocks": len(shock_history),
            "shock_history": shock_history[:20],  # First 20 for brevity
            "bilateral_history_sample": bilateral_history[::12]  # Yearly samples
        }


def run_demo():
    """Demo the integrated simulator."""
    print("=" * 60)
    print("Integrated Simulator Demo")
    print("=" * 60)
    
    # Simple bilateral config
    bilateral_configs = [
        {
            "state_a": "Japan_JAXA",
            "state_b": "China_CNSA",
            "initial_friction": 0.5,
            "initial_cooperation": 0.3,
        }
    ]
    
    sim = IntegratedSimulator(
        consortium_config={},  # Not used in this demo
        bilateral_configs=bilateral_configs,
        coupling_strength=0.3,
        seed=42
    )
    
    results = sim.run_integrated(n_months=120)
    
    print(f"\nSimulated {results['months_simulated']} months")
    print(f"Total bilateral shocks generated: {results['total_shocks']}")
    print(f"\nFinal bilateral states:")
    for dyad, state in results['bilateral_final_states'].items():
        print(f"  {dyad}: friction={state['friction']:.2f}, "
              f"peak={state['peak_friction']:.2f}, "
              f"crisis_months={state['months_in_crisis']}")
    
    if results['shock_history']:
        print(f"\nSample shocks (first 5):")
        for shock in results['shock_history'][:5]:
            print(f"  Month {shock['month']}: {shock['type']} "
                  f"intensity={shock['intensity']:.2f}")


if __name__ == "__main__":
    run_demo()
